name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    container: node:14-buster

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Prettier
        run: npm run prettier

      - name: ESLint
        run: npm run lint

      - name: commitlint
        run: npm run commitlint:all

      - name: Pack
        run: npm pack --dry-run

      - name: Decrypt PGP key
        run: ./.github/scripts/decrypt.sh

      - name: Setup git
        run: ./.github/scripts/git.sh

      - name: Release
        run: npm run release

      - name: Cleanup
        run: ./.github/scripts/cleanup.sh

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
      GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
      NPM_CONFIG_UNSAFE_PERM: true
      NPM_CONFIG_ACCESS: true
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      PRIVATE_KEY_PASSPHRASE: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
